package groupAA;

import core.AbstractGameState;
import core.AbstractPlayer;

public class SushiGoAgentGroupAA extends AbstractPlayer {
  
  public SushiGoAgentGroupAA() {
        this(System.currentTimeMillis()); //system's current time
  }
  
  public SushiGoAgentGroupAA(long randomSeed) {
      //calling AbstractPlayer (super class) args constructor
      super(new AMAF_Params(), "GroupAA MCTS Agent"); 
      //TODO: Create MyAgentGroupAAParams class to set params for this agent 
      //TODO: Experiment and define parameter values for our MCTS in AMAF_Params

      parameters.setRandomSeed(randomSeed);
      randomSeed = new Random(randomSeed);   
  }

  @Override
  public AbstractAction _getAction(AbstractGameState gameState, List<AbstractAction> actions) {
    //TODO: return best action generated by MCTS
  }

  @Override
  public AMAF_Params getParameters() {
    //TODO: return the parameter values for the MCTS
  }

  @Override
  public String toString() {
    return "GroupAA MCTS Agent";
  }

  @Override
  public SushiGoAgentGroupAA copy() {
    AMAF_Params parametersCopy = (AMAF_Params) parameters.copy();
    SushiGoAgentGroupAA agentCopy = new SushiGoAgentGroupAA(parametersCopy);
    return agentCopy;
  }
